### ISSUE TITLE
[MINSTALL-132] Build Failed: Could not install dependency in Maven

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-install-plugin#162]
**[jegadeesh](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jegadeesh)** opened **[MINSTALL-132](https://issues.apache.org/jira/browse/MINSTALL-132?redirect=false)** and commented

When i to install maven plugin  i got below error message on screen

Command i used is

```
1. mvn -X -e  install:install-file -Dfile=/home/jegadeesh/maven-javadoc-plugin-2.10.4.jar  -DgroupID=org.apache.maven.plugins  -DartifactoryID=maven-javadoc-plugin -Dversion=2.10.4 -Dpackaging=jar  -DgeneratePom=true
```

Error i got

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (default-cli) on project standalone-pom: The artifact information is incomplete or not valid:
[ERROR] [0]  'groupId' is missing.
[ERROR] [1]  'artifactId' is missing.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (default-cli) on project standalone-pom: The artifact information is incomplete or not valid:
  [0]  'groupId' is missing.
  [1]  'artifactId' is missing.

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: The artifact information is incomplete or not valid:
  [0]  'groupId' is missing.
  [1]  'artifactId' is missing.

        at org.apache.maven.plugin.install.InstallFileMojo.validateArtifactInformation(InstallFileMojo.java:386)
        at org.apache.maven.plugin.install.InstallFileMojo.execute(InstallFileMojo.java:207)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

---

**Affects:** 2.5.2

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I would expect that the message is quite clear:

```
Caused by: org.apache.maven.plugin.MojoExecutionException: The artifact information is incomplete or not valid:
  [0]  'groupId' is missing.
  [1]  'artifactId' is missing.
```

You provided this as arguments:
`-DgroupID=org.apache.maven.plugins  -DartifactoryID=maven-javadoc-plugin`

So use the right keys for both arguments and it'll work fine.

ps off-topic: why trying to install the maven-javadoc-plugin like this instead of letting Maven downloading it from central?

**Comment by jira-importer** [comment]
**[jegadeesh](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jegadeesh)** commented

Now i got different exception when i am build my project again

Command
mvn clean install

Error :

[ERROR] Failed to execute goal com.github.github:downloads-maven-plugin:0.6:upload (default) on project github-maven-example: Execution default of goal com.github.github:downloads-maven-plugin:0.6:upload failed: An API incompatibility was encountered while executing com.github.github:downloads-maven-plugin:0.6:upload: java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.github:downloads-maven-plugin:0.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/root/.m2/repository/com/github/github/downloads-maven-plugin/0.6/downloads-maven-plugin-0.6.jar
[ERROR] urls[1] = file:/root/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[2] = file:/root/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[3] = file:/root/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[4] = file:/root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[5] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
[ERROR] urls[6] = file:/root/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[7] = file:/root/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[8] = file:/root/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[9] = file:/root/.m2/repository/org/eclipse/mylyn/github/org.eclipse.egit.github.core/1.3.6/org.eclipse.egit.github.core-1.3.6.jar
[ERROR] urls[10] = file:/root/.m2/repository/com/google/code/gson/gson/2.1/gson-2.1.jar
[ERROR] urls[11] = file:/root/.m2/repository/com/github/github/github-maven-core/0.5/github-maven-core-0.5.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by jira-importer** [comment]
**[Guillaume Boué](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gboue)** commented

This isn't an error related to the Install plugin, but the `downloads-maven-plugin`. The `upload` goal in version 0.6 was apparently built for Maven 3.0 and doesn't handle running it with a Maven version higher than 3.1. It also seems this [plugin isn't supported anymore](https://github.com/github/maven-plugins/issues/41).

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

try wagon-maven-plugin or vfs-maven-plugin at mojohaus github
