### ISSUE TITLE
[MINSTALL-80] Errors installing very minimal war

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-install-plugin#187]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** opened **[MINSTALL-80](https://issues.apache.org/jira/browse/MINSTALL-80?redirect=false)** and commented

When certain directories don't exist in a war project, install fails. The failure is somewhat different depending upon the maven-install-plugin version used. The included pom.xml illustrates the behavior with version 2.3.1 which gives the error:

The packaging for this project did not assign a file to the build artifact

org.apache.maven.lifecycle.LifecycleExecutionException: The packaging for this project did not assign a file to the build artifact
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: The packaging for this project did not assign a file to the build artifact
at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:124)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)

With version 2.2 of the plugin the error says:

Error installing artifact: File D:\mydir\Test\target\classes does not exist

org.apache.maven.lifecycle.LifecycleExecutionException: Error installing artifact: File D:\mydir\Test\target\classes does not exist
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error installing artifact: File D:\mydir\Test\target\classes does not exist
at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:143)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
Caused by: org.apache.maven.artifact.installer.ArtifactInstallationException: Error installing artifact: File D:\mydir\Test\target\classes does not exist
at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:119)
at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:105)
... 19 more
Caused by: java.io.IOException: File D:\UserData\Projects\Test\target\classes does not exist
at hidden.org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:1003)
at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:98)

---

**Affects:** 2.2, 2.3, 2.3.1

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12716621/pom.xml) (_988 bytes_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> The packaging for this project did not assign a file to the build artifact
> This pretty says all, either remove `<primaryArtifact>false</primaryArtifact>` from the POM or have the project produce some other kind of main artifact.

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

The attached pom was  a simplified test case to illustrate the issue. The actual pom is copying an applet jar and its dependencies into a directory. This war is then merged into a larger war.

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

Here is the plugin piece that is used.

    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-dependency-plugin</artifactId>
      <executions>
        <execution>
          <phase>process-resources</phase>
          <goals>
            <goal>copy-dependencies</goal>
          </goals>
          <configuration>
            <outputDirectory>${applet.directory}</outputDirectory>
            <stripVersion>true</stripVersion>
          </configuration>
        </execution>
      </executions>
    </plugin>

**Comment by jira-importer** [comment]
**[Mike Calmus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcalmus)** commented

Please take a look at the additional information posted. This is still causing an issue for us.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

From the provided information, the resolution is "wrong plugin configuration by user", the project didn't get its main artifact set by any packaging plugin, nor are there attached artifacts, so the Install Plugin fails as expected during install.
