### ISSUE TITLE
[MINSTALL-10] Build ERROR and build FAILURE occurs

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-install-plugin#208]
**[Hariharan Jagadeesan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=harihag)** opened **[MINSTALL-10](https://issues.apache.org/jira/browse/MINSTALL-10?redirect=false)** and commented

when i try to do "mvn install it says Build ERROR.
This was the error i got.

C:\Program Files\Apache Group\maven-2.0.2\bin>mvn install
[INFO] Scanning for projects...
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Building Maven Default Project
[INFO]    task-segment: [install]
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] BUILD ERROR
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Cannot execute mojo: resources. It requires a project with an existing po
m.xml, but the build is not using one.
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] For more information, run Maven with the -e switch
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Total time: 2 seconds
[INFO] Finished at: Thu Jan 19 19:15:36 IST 2006
[INFO] Final Memory: 2M/4M
[INFO] -------------------------------------------------------------------------
&mdash;

this asks me to run Maven with the  -e switch. But when i try that it sats Build FAILURE.

+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] -------------------------------------------------------------------------
  &mdash;
  [ERROR] BUILD FAILURE
  [INFO] -------------------------------------------------------------------------
  &mdash;
  [INFO] You must specify at least one goal. Try 'install'
  [INFO] -------------------------------------------------------------------------
  &mdash;
  [INFO] Trace
  org.apache.maven.BuildFailureException: You must specify at least one goal. Try
  'install'
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
  fecycleExecutor.java:131)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
  java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
  sorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

      at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Total time: < 1 second
[INFO] Finished at: Thu Jan 19 17:55:05 IST 2006
[INFO] Final Memory: 1M/2M
[INFO] -------------------------------------------------------------------------
&mdash;

---

**Affects:** 2.0

**Attachments:**
- [attachment.txt](https://issues.apache.org/jira/secure/attachment/12716597/attachment.txt) (_3.11 kB_)
- [screenshot-1.jpg](https://issues.apache.org/jira/secure/attachment/12716623/screenshot-1.jpg) (_149.14 kB_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

fixing filing
