### ISSUE TITLE
[MINSTALL-98] installAtEnd broken with parallel builds

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-install-plugin#234]
**[Matt Nelson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mn014019)** opened **[MINSTALL-98](https://issues.apache.org/jira/browse/MINSTALL-98?redirect=false)** and commented

I updated my reactor to depend on install-2.5 and deploy-2.8 to take advantage of the new installAtEnd(MINSTALL-93) and deployAtEnd(MDEPLOY-157) features. When I build the reactor in a single thread, it succeeds. When I build the reactor parallel (-T 2C) it fails every time.

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5:install (default-install) on project my-server: The packaging for this project did not assign a file to the build artifact
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:167)
	at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:163)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: org.apache.maven.plugin.MojoExecutionException: The packaging for this project did not assign a file to the build artifact
	at org.apache.maven.plugin.install.InstallMojo.installProject(InstallMojo.java:194)
	at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:121)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 13 more
```

---

**Affects:** 2.5

**Issue Links:**
- [MDEPLOY-169](https://issues.apache.org/jira/browse/MDEPLOY-169) deployAtEnd broken with parallel builds

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [r1529287](http://svn.apache.org/r1529287)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Probably I can start the release procedure next week
